version: '3.8'

services:
  # api:
  #   container_name: video_service_api
  #   image: video_service_api
  #   build:
  #     context: .
  #     target: production
  #     dockerfile: ./Dockerfile
  #   command: npm run start
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - video_service_network
  #   restart: unless-stopped
  #   volumes:
  #     - .:/api
  db:
    image: mysql
    container_name: mysql-video_service
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service
      MYSQL_USER: service
      MYSQL_PASSWORD: password